### ISSUE TITLE
There is no documentation for the contribution process.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/kipit#28]
You could use this document as a reference:

https://github.com/andela/hairven/blob/staging/CONTRIBUTING.md

**Comment by andela-ioraelosi** [comment]
This article details how to add a commit message template to your system (UNIX):

[Git commit message template](http://adamsimpson.net/writing/git-commit-template)

**Comment by andela-ioraelosi** [comment]
You can find a sample git commit message template here: [template](https://github.com/sparkbox/how_to/tree/master/style/git)

**Comment by emmyakin** [comment]
@andela-rekemezie
