### ISSUE TITLE
There is no README for the application.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/kipit#29]

**Comment by andela-ioraelosi** [comment]
You could use this article as a reference:

http://blog.nodejitsu.com/how-to-write-a-readme/

**Comment by andela-ioraelosi** [comment]
The README for AngularJS is a good example although not as detailed as we might want:

https://github.com/angular/angular.js/blob/master/README.md

**Comment by andela-ioraelosi** [comment]
@andela-blawrence

**Comment by andela-ioraelosi** [comment]
Angular link is dead.

**Comment by maryambabalola** [comment]
@andela-blawrence
