### ISSUE TITLE
Create a DAO factory to interface with the PostgreSQL database.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/kipit#45]
The instructions will be a little less detailed to help prepare you to handle ambiguity as well as research. Acceptance criteria will be defined instead.
# Acceptance Criteria
- [x] Tests must be defined for the DAO factory. The tests should cover the `createDAO` method as well as basic methods of the created DAO (`find`, `findAll`, `delete`).
- [x] The DAO factory must accept only two arguments: the database connection instance (`db`) and the configuration for the created DAO. The options will contain such things as the model name, the table name, the primary key e.t.c
- [x] The DAO factory must be a factory function and not an object prototype.
- [x] The DAO factory should be a utility library.
# Optional Criteria
- The DAO factory should be able to create DAOs that handle complex search queries.

**Comment by emmyakin** [comment]
@andela-rekemezie
