### ISSUE TITLE
Create ER diagram for application and create corresponding configuration for application models.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/kipit#49]
# Acceptance Criteria
- [ ] Database schema diagram should be viewable in _MySQL Workbench_.
- [ ] There should be use case model diagrams for the `general user` and `admin user`.
- [ ] There should be a data model for the application that includes the `transactions`, `accounts` and `users` tables with relevant relationships.

**Comment by bolutife-lawrence** [comment]
@andela-mbabalola
